// <auto-generated />
namespace FirewallWidget.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class docking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(docking));
        
        string IMigrationMetadata.Id
        {
            get { return "202006251426381_docking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
