// <auto-generated />
namespace FirewallWidget.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class options__rulesidx_name_dir_profile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(options__rulesidx_name_dir_profile));
        
        string IMigrationMetadata.Id
        {
            get { return "202006161556125_options__rules-idx_name_dir_profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
