// <auto-generated />
namespace FirewallWidget.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addruledirection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addruledirection));
        
        string IMigrationMetadata.Id
        {
            get { return "202004120002584_add-rule-direction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
